# Generated by Django 2.1.3 on 2019-03-09 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20190303_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='user',
        ),
        migrations.AddField(
            model_name='authentication',
            name='black_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authentication',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='authentic_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
